using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Chameleon.DTOs.Inventory
{
  public class GetInventoryFeedsItemDTO
  {
    public long InvFeedsReportItemId { get; set; }
    public int ItemNoId { get; set; }
    public string ItemStatus { get; set; }
    public int ItemStatusId { get; set; }
    public string ItemName { get; set; }
    public int AppliedFeedingRuleNoBanc { get; set; }
    public string AppliedFeedingRuleTypeBanc { get; set; }
    public int AppliedFeedingRuleNoMainsl { get; set; }
    public string AppliedFeedingRuleTypeMainsl { get; set; }
    //public int AppliedFeedingRuleNoSWCAFT { get; set; }
    //public string AppliedFeedingRuleTypeSWCAFT { get; set; }
    public int AppliedFeedingRuleNoBasc { get; set; }
    public string AppliedFeedingRuleTypeBasc { get; set; }
    public int? AppliedFeedingRuleNoPrismCast { get; set; }
    public string AppliedFeedingRuleTypePrismCast { get; set; }
    public int? AppliedFeedingRuleNoPrismCalt { get; set; }
    public string AppliedFeedingRuleTypePrismCalt { get; set; }
    public int? AppliedFeedingRuleNoZinusTracy { get; set; }
    public string AppliedFeedingRuleTypeZinusTracy { get; set; }
    public int? AppliedFeedingRuleNoZinusChs { get; set; }
    public string AppliedFeedingRuleTypeZinusChs { get; set; }
    public string CustItemName { get; set; }
    public int QtyAvailBanc { get; set; }
    public int QtyAvailActualBanc { get; set; }
    public int QtyOnHandBanc { get; set; }
    public int QtyAvailMainsl { get; set; }
    public int QtyAvailActualMainsl { get; set; }
    public int QtyOnHandMainsl { get; set; }
    //public int QtyAvailSWCAFT { get; set; }
    //public int QtyAvailActualSWCAFT { get; set; }
    //public int QtyOnHandSWCAFT { get; set; }
    public int QtyAvailBasc { get; set; }
    public int QtyAvailActualBasc { get; set; }
    public int QtyOnHandBasc { get; set; }
    public int QtyAvailPrismCast { get; set; }
    public int QtyAvailActualPrismCast { get; set; }
    public int QtyOnHandPrismCast { get; set; }
    public int QtyAvailPrismCalt { get; set; }
    public int QtyAvailActualPrismCalt { get; set; }
    public int QtyOnHandPrismCalt { get; set; }
    public int QtyAvailZinusTracy { get; set; }
    public int QtyAvailActualZinusTracy { get; set; }
    public int QtyOnHandZinusTracy { get; set; }
    public int QtyAvailZinusChs { get; set; }
    public int QtyAvailActualZinusChs { get; set; }
    public int QtyOnHandZinusChs { get; set; }
    public int QtyAvailAmzInv { get; set; }
    public int QtyOnHandAmzInv { get; set; }
    public int QtyAvailCGInv { get; set; }
    public int QtyOnHandGCInv { get; set; }
    public bool BancFeedable { get; set; }
    public bool MainslFeedable { get; set; }
    //public bool SWCAFTFeedable { get; set; }
    public bool BascFeedable { get; set; }
    public bool PrismCastFeedable { get; set; }
    public bool PrismCaltFeedable { get; set; }
    public bool ZinusTracyFeedable { get; set; }
    public bool ZinusChsFeedable { get; set; }
    public string AmazonCustSKU { get; set; }
    public int AmazonQtyBanc { get; set; }
    public int AmazonQtyMainsl { get; set; }
    //public int AmazonQtySWCAFT { get; set; }
    public int AmazonQtyBasc { get; set; }
    public int AmazonQtyPrismCast { get; set; }
    public int AmazonQtyPrismCalt { get; set; }
    public int AmazonQtyZinusTracy { get; set; }
    public int AmazonQtyZinusChs { get; set; }
    public int AmazonPercentage { get; set; }
    public int AmazonBancPercentage { get; set; }
    public int AmazonMainslPercentage { get; set; }
    //public int AmazonSWCAFTPercentage { get; set; }
    public int AmazonBascPercentage { get; set; }
    public int AmazonPrismCastPercentage { get; set; }
    public int AmazonPrismCaltPercentage { get; set; }
    public int AmazonZinusTracyPercentage { get; set; }
    public int AmazonZinusChsPercentage { get; set; }
    public bool AmazonFeedable { get; set; }
    public int AmazonDupCount { get; set; }
    public string WayfairCustSKU { get; set; }
    public int WayfairQtyBanc { get; set; }
    public int WayfairQtyMainsl { get; set; }
    //public int WayfairQtySWCAFT { get; set; }
    public int WayfairQtyBasc { get; set; }
    public int WayfairQtyPrismCast { get; set; }
    public int WayfairQtyPrismCalt { get; set; }
    public int WayfairQtyZinusTracy { get; set; }
    public int WayfairQtyZinusChs { get; set; }
    public int WayfairPercentage { get; set; }
    public bool WayfairFeedable { get; set; }
    public int WayfairDupCount { get; set; }
    public int WayfairBancPercentage { get; set; } 
    public int WayfairMainslPercentage { get; set; }
    //public int WayfairSWCAFTPercentage { get; set; }
    public int WayfairBascPercentage { get; set; }
    public int WayfairPrismCastPercentage { get; set; }
    public int WayfairPrismCaltPercentage { get; set; }
    public int WayfairZinusTracyPercentage { get; set; }
    public int WayfairZinusChsPercentage { get; set; }
    public string WalmartCustSKU { get; set; }
    public int WalmartQtyBanc { get; set; }
    public int WalmartQtyMainsl { get; set; }
    //public int WalmartQtySWCAFT { get; set; }
    public int WalmartQtyBasc { get; set; }
    public int WalmartQtyPrismCast { get; set; }
    public int WalmartQtyPrismCalt { get; set; }
    public int WalmartQtyZinusTracy { get; set; }
    public int WalmartQtyZinusChs { get; set; }
    public int WalmartPercentage { get; set; }
    public bool WalmartFeedable { get; set; }
    public int WalmartDupCount { get; set; }
    public int WalmartBancPercentage { get; set; }
    public int WalmartMainslPercentage { get; set; }
    //public int WalmartSWCAFTPercentage { get; set; }
    public int WalmartBascPercentage { get; set; }
    public int WalmartPrismCastPercentage { get; set; }
    public int WalmartPrismCaltPercentage { get; set; }
    public int WalmartZinusTracyPercentage { get; set; }
    public int WalmartZinusChsPercentage { get; set; }
    public string OverstockCustSKU { get; set; }
    public int OverstockQtyBanc { get; set; }
    public int OverstockQtyMainsl { get; set; }
    //public int OverstockQtySWCAFT { get; set; }
    public int OverstockQtyBasc { get; set; }
    public int OverstockQtyPrismCast { get; set; }
    public int OverstockQtyPrismCalt { get; set; }
    public int OverstockQtyZinusTracy { get; set; }
    public int OverstockQtyZinusChs { get; set; }
    public int OverstockPercentage { get; set; }
    public bool OverstockFeedable { get; set; }
    public int OverstockDupCount { get; set; } 
    public int OverstockBancPercentage { get; set; }
    public int OverstockMainslPercentage { get; set; }
    //public int OverstockSWCAFTPercentage { get; set; }
    public int OverstockBascPercentage { get; set; }
    public int OverstockPrismCastPercentage { get; set; }
    public int OverstockPrismCaltPercentage { get; set; }
    public int OverstockZinusTracyPercentage { get; set; }
    public int OverstockZinusChsPercentage { get; set; }
    public string eBayCustSKU { get; set; }
    public int eBayQtyBanc { get; set; }
    public int eBayQtyMainsl { get; set; }
    //public int eBayQtySWCAFT { get; set; }
    public int eBayQtyBasc { get; set; }
    public int eBayQtyPrismCast { get; set; }
    public int eBayQtyPrismCalt { get; set; }
    public int eBayQtyZinusTracy { get; set; }
    public int eBayQtyZinusChs { get; set; }
    public int eBayPercentage { get; set; }
    public bool eBayFeedable { get; set; }
    public int eBayDupCount { get; set; }
    public int eBayBancPercentage { get; set; }
    public int eBayMainslPercentage { get; set; }
    //public int eBaySWCAFTPercentage { get; set; }
    public int eBayBascPercentage { get; set; }
    public int eBayPrismCastPercentage { get; set; }
    public int eBayPrismCaltPercentage { get; set; }
    public int eBayZinusTracyPercentage { get; set; }
    public int eBayZinusChsPercentage { get; set; }
    public string BPMWebCustSKU { get; set; }
    public int BPMWebQtyBanc { get; set; }
    public int BPMWebQtyMainsl { get; set; }
    //public int BPMWebQtySWCAFT { get; set; }
    public int BPMWebQtyBasc { get; set; }
    public int BPMWebQtyPrismCast { get; set; }
    public int BPMWebQtyPrismCalt { get; set; }
    public int BPMWebQtyZinusTracy { get; set; }
    public int BPMWebQtyZinusChs { get; set; }
    public int BPMWebPercentage { get; set; }
    public bool BPMFeedable { get; set; }
    public int BPMDupCount { get; set; }
    public int BPMWebBancPercentage { get; set; }
    public int BPMWebMainslPercentage { get; set; }
    //public int BPMWebSWCAFTPercentage { get; set; }
    public int BPMWebBascPercentage { get; set; }
    public int BPMWebPrismCastPercentage { get; set; }
    public int BPMWebPrismCaltPercentage { get; set; }
    public int BPMWebZinusTracyPercentage { get; set; }
    public int BPMWebZinusChsPercentage { get; set; }
    public string MellowWebCustSKU { get; set; }
    public int MellowWebQtyBanc { get; set; }
    public int MellowWebQtyMainsl { get; set; }
    //public int MellowWebQtySWCAFT { get; set; }
    public int MellowWebQtyBasc { get; set; }
    public int MellowWebQtyPrismCast { get; set; }
    public int MellowWebQtyPrismCalt { get; set; }
    public int MellowWebQtyZinusTracy { get; set; }
    public int MellowWebQtyZinusChs { get; set; }
    public int MellowWebPercentage { get; set; }
    public bool MellowFeedable { get; set; }
    public int MellowDupCount { get; set; }
    public int MellowWebBancPercentage { get; set; }
    public int MellowWebMainslPercentage { get; set; }
    //public int MellowWebSWCAFTPercentage { get; set; }
    public int MellowWebBascPercentage { get; set; }
    public int MellowWebPrismCastPercentage { get; set; }
    public int MellowWebPrismCaltPercentage { get; set; }
    public int MellowWebZinusTracyPercentage { get; set; }
    public int MellowWebZinusChsPercentage { get; set; }
    public string HouzzCustSKU { get; set; }
    public int HouzzQtyBanc { get; set; }
    public int HouzzQtyMainsl { get; set; }
    //public int HouzzQtySWCAFT { get; set; }
    public int HouzzQtyBasc { get; set; }
    public int HouzzPercentage { get; set; }
    public bool HouzzFeedable { get; set; }
    public int HouzzDupCount { get; set; }
    public int HouzzBancPercentage { get; set; }
    public int HouzzMainslPercentage { get; set; }
    //public int HouzzSWCAFTPercentage { get; set; }
    public int HouzzBascPercentage { get; set; }
    public string HomeDepotCustSKU { get; set; }
    public int HomeDepotQtyBanc { get; set; }
    public int HomeDepotQtyMainsl { get; set; }
    //public int HomeDepotQtySWCAFT { get; set; }
    public int HomeDepotQtyBasc { get; set; }
    public int HomeDepotQtyPrismCast { get; set; }
    public int HomeDepotQtyPrismCalt { get; set; }
    public int HomeDepotQtyZinusTracy { get; set; }
    public int HomeDepotQtyZinusChs { get; set; }
    public int HomeDepotPercentage { get; set; }
    public bool HomeDepotFeedable { get; set; }
    public int HomeDepotDupCount { get; set; }
    public int HomeDepotBancPercentage { get; set; }
    public int HomeDepotMainslPercentage { get; set; }
    //public int HomeDepotSWCAFTPercentage { get; set; }
    public int HomeDepotBascPercentage { get; set; }
    public int HomeDepotPrismCastPercentage { get; set; }
    public int HomeDepotPrismCaltPercentage { get; set; }
    public int HomeDepotZinusTracyPercentage { get; set; }
    public int HomeDepotZinusChsPercentage { get; set; }
    public string TargetCustSKU { get; set; }
    public int TargetQtyBanc { get; set; }
    public int TargetQtyMainsl { get; set; }
    //public int TargetQtySWCAFT { get; set; }
    public int TargetQtyBasc { get; set; }
    public int TargetQtyPrismCast { get; set; }
    public int TargetQtyPrismCalt { get; set; }
    public int TargetQtyZinusTracy { get; set; }
    public int TargetQtyZinusChs { get; set; }
    public int TargetPercentage { get; set; }
    public bool TargetFeedable { get; set; }
    public int TargetDupCount { get; set; }
    public int TargetBancPercentage { get; set; }
    public int TargetMainslPercentage { get; set; }
    //public int TargetSWCAFTPercentage { get; set; }
    public int TargetBascPercentage { get; set; }
    public int TargetPrismCastPercentage { get; set; }
    public int TargetPrismCaltPercentage { get; set; }
    public int TargetZinusTracyPercentage { get; set; }
    public int TargetZinusChsPercentage { get; set; }
    public int etcMarketQty { get; set; }
    public int etcMarketPercentage { get; set; }
    public int totalStagePOQtyBanc { get; set; }
    public int totalStagePOQtyMainsl { get; set; }
    //public int totalStagePOQtySWCAFT { get; set; }
    public int totalStagePOQtyBasc { get; set; }
    public int totalStagePOQtyPrismCast { get; set; }
    public int totalStagePOQtyPrismCalt { get; set; }
    public int totalStagePOQtyZinusTracy { get; set; }
    public int totalStagePOQtyZinusChs { get; set; }
    public int leftOverQtyBanc { get; set; }
    public int leftOverQtyMainsl { get; set; }
    //public int leftOverQtySWCAFT { get; set; }
    public int leftOverQtyBasc { get; set; }
    public int leftOverQtyPrismCast { get; set; }
    public int leftOverQtyPrismCalt { get; set; }
    public int leftOverQtyZinusTracy { get; set; }
    public int leftOverQtyZinusChs { get; set; }
    public bool isCooMasterSku { get; set; }
    public bool hasCooSlaveSku { get; set; }
    public int cooSlaveSkuId { get; set; }
		public int cooMasterSkuId { get; set; }
		public bool AmazonRule { get; set; }
		public bool eBayRule { get; set; }
		public bool WalmartRule { get; set; }
		public bool WayfairRule { get; set; }
		public bool BPMRule { get; set; }
		public bool MellowRule { get; set; }
		public bool TargetRule { get; set; }
		public bool HomeDepotRule { get; set; }
		public bool OverstockRule { get; set; }
    public bool HasMkIcrNotCooMaster { get; set; }
		// Not using
		public int countParetoA { get; set; }
    public int countParetoB { get; set; }
    public int countParetoC { get; set; }
    public int paretoAqty { get; set; }
    public int paretoBqty { get; set; }
  }
}
