namespace Chameleon.DTOs.Inventory
{
  public class UserRevisedInvFeedsDTO
  {
    public string sku { get; set; }
    public int qtyAvailBanc { get; set; }
    public int qtyAvailBasc { get; set; }
    public int qtyAvailMainsl { get; set; }
   // public int qtyAvailSwcaft { get; set; }
    public int qtyAvailPrismCast { get; set; }
    public int qtyAvailPrismCalt { get; set; }
    public int qtyAvailZinusTracy { get; set; }
    public int qtyAvailZinusChs { get; set; }
    public int qtyAvailCastleGate { get; set; }
    public int totalStagePOQtyBanc { get; set; }
    public int totalStagePOQtyBasc { get; set; }

    public int totalStagePOQtyMainsl { get; set; }
    //public int totalStagePOQtySwcaft { get; set; }
    public int totalStagePOQtyPrismCast { get; set; }
    public int totalStagePOQtyPrismCalt { get; set; }
    public int totalStagePOQtyZinusTracy { get; set; }
    public int totalStagePOQtyZinusChs { get; set; }
    public int amazonQtyBanc { get; set; }
    public int amazonQtyBasc { get; set; }
    public int amazonQtyMainsl { get; set; }
    //public int amazonQtySwcaft { get; set; }
    public int amazonQtyPrismCast { get; set; }
    public int amazonQtyPrismCalt { get; set; }
    public int amazonQtyZinusTracy { get; set; }
    public int amazonQtyZinusChs { get; set; }
    public int walmartQtyBanc { get; set; }
    public int walmartQtyBasc { get; set; }
    public int walmartQtyMainsl { get; set; }
    //public int walmartQtySwcaft { get; set; }
    public int walmartQtyPrismCast { get; set; }
    public int walmartQtyPrismCalt { get; set; }
    public int walmartQtyZinusTracy { get; set; }
    public int walmartQtyZinusChs { get; set; }
    public int wayfairQtyBanc { get; set; }
    public int wayfairQtyBasc { get; set; }
    public int wayfairQtyMainsl { get; set; }
   // public int wayfairQtySwcaft { get; set; }
    public int wayfairQtyPrismCast { get; set; }
    public int wayfairQtyPrismCalt { get; set; }
    public int wayfairQtyZinusTracy { get; set; }
    public int wayfairQtyZinusChs { get; set; }
    public int homeDepotQtyBanc { get; set; }
    public int homeDepotQtyBasc { get; set; }
    public int homeDepotQtyMainsl { get; set; }
    //public int homeDepotQtySwcaft { get; set; }
    public int homeDepotQtyPrismCast { get; set; }
    public int homeDepotQtyPrismCalt { get; set; }
    public int homeDepotQtyZinusTracy { get; set; }
    public int homeDepotQtyZinusChs { get; set; }
    public int overstockQtyBanc { get; set; }
    public int overstockQtyBasc { get; set; }
    public int overstockQtyMainsl { get; set; }
    //public int overstockQtySwcaft { get; set; }
    public int overstockQtyPrismCast { get; set; }
    public int overstockQtyPrismCalt { get; set; }
    public int overstockQtyZinusTracy { get; set; }
    public int overstockQtyZinusChs { get; set; }
    public int targetQtyBanc { get; set; }
    public int targetQtyBasc { get; set; }
    public int targetQtyMainsl { get; set; }
    //public int targetQtySwcaft { get; set; }
    public int targetQtyPrismCast { get; set; }
    public int targetQtyPrismCalt { get; set; }
    public int targetQtyZinusTracy { get; set; }
    public int targetQtyZinusChs { get; set; }
    public int eBayQtyBanc { get; set; }
    public int eBayQtyBasc { get; set; }
    public int eBayQtyMainsl { get; set; }
    //public int eBayQtySwcaft { get; set; }
    public int eBayQtyPrismCast { get; set; }
    public int eBayQtyPrismCalt { get; set; }
    public int eBayQtyZinusTracy { get; set; }
    public int eBayQtyZinusChs { get; set; }
    public int bpmQtyBanc { get; set; }
    public int bpmQtyBasc { get; set; }
    public int bpmQtyMainsl { get; set; }
    //public int bpmQtySwcaft { get; set; }
    public int bpmQtyPrismCast { get; set; }
    public int bpmQtyPrismCalt { get; set; }
    public int bpmQtyZinusTracy { get; set; }
    public int bpmQtyZinusChs { get; set; }
    public int mellowQtyBanc { get; set; }
    public int mellowQtyBasc { get; set; }
    public int mellowQtyMainsl { get; set; }
    //public int mellowQtySwcaft { get; set; }
    public int mellowQtyPrismCast { get; set; }
    public int mellowQtyPrismCalt { get; set; }
    public int mellowQtyZinusTracy { get; set; }
    public int mellowQtyZinusChs { get; set; }
    public int houzzQtyBanc { get; set; }
    public int houzzQtyBasc { get; set; }
    public int houzzQtyMainsl { get; set; }
    public int houzzQtySwcaft { get; set; }
  }
}
